=== snacktavish/bio-dimsum/DimSum2/src/ConfigFile.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:simpleType name="edgeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="impenetrable"/>
			<xs:enumeration value="deadly"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="fileType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="image"/>
			<xs:enumeration value="file"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="treeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="parent"/>
			<xs:enumeration value="distance"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="locType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="all"/>
			<xs:enumeration value="last"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="xyType">
		<xs:sequence>
		<xs:element name="data" minOccurs="1" maxOccurs="unbounded">
			<xs:complexType>
			<xs:attribute name="type" type="fileType" use="required"/>
			<xs:attribute name="maxvalue" type="xs:int" use="required"/>
			<xs:attribute name="file" type="xs:string" use="required"/>
			<xs:attribute name="startgeneration" type="xs:int"/>
			<xs:attribute name="endgeneration" type="xs:int"/>
			</xs:complexType>
		</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:simpleType name="intlist">
    	<xs:list itemType="xs:float"/>
	</xs:simpleType>
	
	<xs:complexType name="pType">
		<xs:sequence>
		<xs:element name="distribution" minOccurs="1" maxOccurs="unbounded">
			<xs:complexType>
			<xs:attribute name="p" type="intlist" use="required"/>
			<xs:attribute name="offspring" type="intlist" use="required"/>	
			<xs:attribute name="startgeneration" type="xs:int"/>
			<xs:attribute name="endgeneration" type="xs:int"/>
			</xs:complexType>
		</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	
	
<xs:element name="simulation">
	<xs:complexType>
		<xs:sequence>

	
	<xs:element name="seed" type="xs:int" />
	
	<xs:element name="generations" type="xs:int"/>	
	
	<xs:element name="latitude">
		<xs:complexType>
		<xs:attribute name="minimum" type="xs:float" use="required"/>
		<xs:attribute name="maximum" type="xs:float" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="longitude">
		<xs:complexType>
		<xs:attribute name="minimum" type="xs:float" use="required"/>
		<xs:attribute name="maximum" type="xs:float" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="edges">
		<xs:complexType>
		<xs:attribute name="type" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="carryingcapacity" type="xyType" />
	<xs:element name="hardborders" type="xyType" />
	<xs:element name="softborders" type="xyType" />
	<xs:element name="reproductiveability" type="pType" />
	<xs:element name="dispersalradius" type="pType" />
	
	<xs:element name="initialpopulation">
		<xs:complexType>
		<xs:sequence>
		<xs:element name="node" minOccurs="1" maxOccurs="unbounded">
			<xs:complexType>
			<xs:attribute name="lat" type="xs:float" use="required"/>
			<xs:attribute name="lon" type="xs:float" use="required"/>
			<xs:attribute name="n" type="xs:int" use="required"/>
			<xs:attribute name="r" type="xs:int" use="required"/>
			<xs:attribute name="g" type="xs:int" use="required"/>
			<xs:attribute name="b" type="xs:int" use="required"/>
			</xs:complexType>
		</xs:element>
		</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="output">
		<xs:complexType>
		<xs:sequence>
			<xs:element name="visual" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:attribute name="output_every" type="xs:int" use="required"/>
					<xs:attribute name="xsize" type="xs:int"/>
					<xs:attribute name="ysize" type="xs:int"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="treestructure" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="delimeter" type="xs:string"/>
					<xs:attribute name="output" type="treeType" use="required"/>
					<xs:attribute name="file" type="xs:string" use="required"/>
					<xs:attribute name="trim" type="xs:boolean"/>
					<xs:attribute name="resolve" type="xs:boolean"/>
					<xs:attribute name="mutationrate" type="xs:float"/>
					<xs:attribute name="output_every" type="xs:int" use="required"/>			
				</xs:complexType>
			</xs:element>	
			<xs:element name="locations" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="generation" type="locType" use="required"/>
					<xs:attribute name="file" type="xs:string" use="required"/>
					<xs:attribute name="output_every" type="xs:int" use="required"/>			
				</xs:complexType>
			</xs:element>	
		</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	</xs:sequence>
	<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
</xs:element>
</xs:schema>

=== snacktavish/bio-dimsum/DimSum2/exampleHI.xml
<simulation xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="src/ConfigFile.xsd" name="HawaiiExample">

	<seed> 3452 </seed>

	<generations>100</generations>
	
	
	<latitude minimum="18.5" maximum="22.5"/>
	<longitude minimum="-160.5" maximum="-154.5"/>

	<edges type="impenetrable"/>

	<carryingcapacity>
		<data type="image" maxvalue="1" file="ExampleInputs/ExampleHI.bmp" />
    </carryingcapacity>

	<hardborders>
		<data type="image" maxvalue="1" file="ExampleInputs/ExampleHI.bmp" />
	</hardborders>

	<softborders>		
    	<data type="image"  maxvalue="1" file="ExampleInputs/ExampleHI.bmp" />
    </softborders>
	
	<reproductiveability>
		<distribution offspring="1 2" p=".3 .7"/>
	</reproductiveability>
	
	
	<dispersalradius>
		<distribution offspring="1 7 50 70 " p=".8 .1 .05 .05"/>
	</dispersalradius>

	<initialpopulation>
        <node lat="21.9" lon="-159.5" n="1" r="255" g="255" b="0"/>
        <node lat="21.4" lon="-158" n="1" r="255" g="0" b="0"/>
        <node lat="20.8" lon="-156.3" n="1" r="255" g="90" b="255"/>
        <node lat="19.5" lon="-155.5" n="1" r="30" g="144" b="255"/>
	</initialpopulation>
	
	<output>
		<visual output_every='10' xsize="800" ysize="600"/>
		<treestructure delimeter='#' output='parent' trim='false' file='anc_phylo.tre' output_every='10' resolve='true'/>
		<treestructure delimeter=':' output='distance' mutationrate='0.1' trim='false' file='dist_phylo.tre'  output_every='10' resolve='true'/>
		<locations generation='all' file='locs.txt'  output_every='10'/>
	</output>
	
<!-- A "simulation" end tag is required at the end of the file. -->
	
</simulation>
